### ISSUE TITLE
New TV data source proposal.

### ISSUE THREAD

**Issue by RickyGrassmuck** [lokenx/plex-requests#7]
So I was digging around while I'm at work and came across another TV data website, called tvmaze.com, who's API is much simpler and seems to offer more features than TVDB.

You can get all the details about it from http://www.tvmaze.com/api

A couple things that stood out were:
- it's an open API so no need for an api key or token is needed to call against it
- Uses fuzzy logic to find and return the most relevant results even given slight spelling errors.
- Provides additional series data like seasons, episodes, air time info, posters and trailer links
- Returns the data in a well formatted, easy to parse json object.

Let me know what you think about it, seems to me that it would be perfect for this project.

**Comment by lokenx** [comment]
Interesting find. Important question though, does it return a valid TVDB ID as that's what all the services require.

Answered my own question haha! It does under `externals`. Very interested then!

**Comment by RickyGrassmuck** [comment]
Yup, it returns that plus IMDB and tvrage id's

**Comment by lokenx** [comment]
Now do we add it to this (still not sure if I'll finish) version, or on the current Meteor one.

**Comment by RickyGrassmuck** [comment]
I'm actually working on making a meteor package now using the
themoviedbsearch package as a template. I figured the api is simple enough
that it could be ported over to just about any other framework with minimal
fuss.

**Comment by RickyGrassmuck** [comment]
Been done for a loooong time, probably should be closed lol.
